### ISSUE TITLE
Frost and Unholy rune cooldown displays are swapped incorrectly

### ISSUE THREAD

**Issue by Kata1337** [neotron/WoW-MagicRunes#1]
In WotLK classic beta, when i use a frost rune, the addon displays the use of an unholy rune and its cooldown.\

When i use an unholy rune, the addon displays the use of a frost rune and its cooldown.

This is consistent all the time.  Blood runes and death runes aren't affected and work properly.

**Comment by neotron** [comment]
Thanks- yes I think the runes are flipped (I had to roll back from retail since it doesn't have a rune type per se). Will fix.

**Comment by neotron** [comment]
Fixed.
