### ISSUE TITLE
Masque errors

### ISSUE THREAD

**Issue by Kata1337** [neotron/WoW-MagicRunes#3]
WotLK Beta:

5x AceLocale-3.0-6: MagicRunes: Missing entry for 'Masque'
[string "@MagicRunes\IconDisplay\IconDisplay.lua"]:910: in main chunk

5x AceLocale-3.0-6: MagicRunes: Missing entry for 'The icons are fully integrated with the Masque addon. This addon lets you skin the buttons for a more personalized display.
[string "@MagicRunes\IconDisplay\IconDisplay.lua"]:920: in main chunk

5x AceLocale-3.0-6: MagicRunes: Missing entry for 'To configure the looks, open the Masque configuration UI using the /masque command. Select Addons => Magic Runes => Rune Bars.
[string "@MagicRunes\IconDisplay\IconDisplay.lua"]:921: in main chunk

5x AceLocale-3.0-6: MagicRunes: Missing entry for 'You can find Masque and many different skins on http://wow.curse.com/'
[string "@MagicRunes\IconDisplay\IconDisplay.lua"]:922: in main chunk

**Comment by neotron** [comment]
Localization errors. will look at that as well.

**Comment by neotron** [comment]
Also shouldn't cause errors in release builds so will look at that as well.
