### ISSUE TITLE
Other lua error

### ISSUE THREAD

**Issue by Kata1337** [neotron/WoW-MagicRunes#4]
WotLK Beta:

1x MagicRunes\MagicRunes-1.0.116.lua:539: attempt to index upvalue 'data' (a nil value)
[string "@MagicRunes\MagicRunes-1.0.116.lua"]:539: in function `UpdateRemainingTimes'
[string "@MagicRunes\RuneConfig.lua"]:54: in function <MagicRunes\RuneConfig.lua:54>
[string "=[C]"]: ?
[string "@Ace3\AceConfig-3.0-3\AceConfigDialog-3.0\AceConfigDialog-3.0-82.lua"]:51: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:49>
[string "@Ace3\AceConfig-3.0-3\AceConfigDialog-3.0\AceConfigDialog-3.0-82.lua"]:836: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:657>
[string "=[C]"]: ?
[string "@Ace3\AceGUI-3.0\AceGUI-3.0-41.lua"]:72: in function <Ace3\AceGUI-3.0\AceGUI-3.0.lua:70>
[string "@Ace3\AceGUI-3.0\AceGUI-3.0-41.lua"]:306: in function `Fire'
[string "@Ace3\AceGUI-3.0-41\widgets\AceGUIWidget-CheckBox.lua"]:68: in function <...ns\Ace3\AceGUI-3.0\widgets\AceGUIWidget-CheckBox.lua:57>4s

**Comment by neotron** [comment]
Not sure why this happened but adding a mitigation for it.
